# -*- coding: utf-8 -*-
"""Module_2_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLVgz_8c4xFGwe-nzuGP5vmyZNsJcZ23
"""

import numpy as np
# Task 1: Array Creation and Operations

arr=np.arange(0,21)
print('1D array',arr)

arr2=np.random.randint(10,99,size=(4,5))
print('\n 2D array \n',arr2)

print('\n',np.identity(3,dtype=int))

print("\n mean",arr2.mean())
print("\n median",np.median(arr2))
print("\n standard deviation",arr2.std())


print('\n second row' ,arr2[1])
print('\n third column' ,arr2[:, 2])

arr3=np.random.randint(10,99,size=(4,5))


print('\n Multiply two arrays element-wise\n',arr2*arr3)

# Task 2: Broadcasting and Reshaping
arr3=arr[:16].reshape(4,4)
print("\n Reshape a 1D array \n",arr3)

oned=[1, 2, 3, 4]
print("\nAdd a 1D array [1, 2, 3, 4] to each row of the matrix using broadcasting \n", arr3 + oned)

print("\nFlatten the matrix\n",arr3.flatten())

# Part 2: Pandas – Data Manipulation

import pandas as pd

df=pd.DataFrame({'Name':['Alice','Bob','Charlie','Diana','Evan'], 'Age':[25,30,28,35,40],'Department':['IT','HR','IT','Marketing','HR'],'Salary':[50000,
45000,
72000,
58000,
60000]
})

#  new column Bonus
df['Bonus']=df['Salary']*0.10
print(df,'\n')

dept=df[df['Department']=='HR']
print('\nemployees in the HR department :\n',dept)


avg=df.groupby(['Department'])['Salary'].mean()
print("\nAverage Salary by Department:\n",avg)


df.to_csv('Data Manipulation.csv',index=False)

dff=pd.read_csv('people_data_with_city.csv')
print(dff.head())
print("\n\n",dff.tail())

dff.shape

dff.info()

dff.dropna()
dff.head()

dff.describe()

#Part 3: Classification Evaluation with Confusion Matrix

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Train-test split
X = df[iris.feature_names]
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
#how many predictions were right or wrong for each class

print("\nAccuracy:", accuracy_score(y_test, y_pred))
#how often the model predict correctly

print("Precision:", precision_score(y_test, y_pred, average='weighted'))
# from all positive prediction how many are actually correct

print("Recall:", recall_score(y_test, y_pred, average='weighted'))
# from all positive prediction how many the model found correctly

print("F1-Score:", f1_score(y_test, y_pred, average='weighted'))
# a balance between recall & precision